language: node_js
node_js:
  - "0.10"

before_script:
  - npm install --quiet -g grunt-cli karma bower
  - bower install

script: grunt prod

deploy:
  provider: heroku
  api_key: db181b69-4116-4061-aab9-2d2124fd1eaf
  app: angular-store
